Models/Slipper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Flex_Slippers.Models
{
    public class Slipper
    {
        public int Id { get; set; }

        [StringLength(40, MinimumLength = 5)]
        [Required]
        [Display(Name = "Type of Slippers")]
        [RegularExpression(@"^[A-Z]+[a-zA-Z\s]*$")]
        public string TypeOfProduct { get; set; }

        [StringLength(10)]
        [Required]
        public string Department { get; set; }


        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Price { get; set; }


        [Column(TypeName = "decimal(18, 2)")]
        public decimal Size { get; set; }


        [StringLength(10)]
        [Required]
        public string Width { get; set; }


        [StringLength(20)]
        [Required]
        public string Material { get; set; }


        [Display(Name = "Description of Slipper")]
        [Required]
        [StringLength(500)]
        [RegularExpression(@"^[A-Z]+[a-zA-Z0-9""'\s-]*$")]
        public string DescOfProduct { get; set; }


        [Range(1, 5)]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Rating { get; set; }


        [Display(Name = "Manufacturing Date")]
        [DataType(DataType.Date)]
        public DateTime ManufacturingDt { get; set;  }
    }
}

Controllers/SlippersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Flex_Slippers.Data;
using Flex_Slippers.Models;

namespace Flex_Slippers.Controllers
{
    public class SlippersController : Controller
    {
        private readonly Flex_SlippersContext _context;

        public SlippersController(Flex_SlippersContext context)
        {
            _context = context;
        }

        // GET: Slippers
        /*
        public async Task<IActionResult> Index()
        {
            return View(await _context.Slipper.ToListAsync());
        }
        */

        //-----------------------------------------------------------------------------------

        /*
        public async Task<IActionResult> Index(string searchString)
        {
            var flexslippers = from m in _context.Slipper
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                flexslippers = flexslippers.Where(s => s.Department.Contains(searchString));
            }

            return View(await flexslippers.ToListAsync());
        }
        */

        public async Task<IActionResult> Index(string slipperMaterial, string searchString)
        {
            var flexslippers = from m in _context.Slipper
                         select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                flexslippers = flexslippers.Where(s => s.Department.Contains(searchString));
            }



            // Use LINQ to get list of Material.
            IQueryable<string> MaterialQuery = from m in _context.Slipper
                                               orderby m.Material
                                               select m.Material;

            if (!string.IsNullOrEmpty(slipperMaterial))
            {
                flexslippers = flexslippers.Where(x => x.Material == slipperMaterial);
            }



            var slipperMaterialVM = new SlipperMaterialViewModel
            {
                Materials = new SelectList(await MaterialQuery.Distinct().ToListAsync()),
                Slippers = await flexslippers.ToListAsync()
            };

            return View(slipperMaterialVM);
        }

        //-----------------------------------------------------------------------------------

        // GET: Slippers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slipper = await _context.Slipper
                .FirstOrDefaultAsync(m => m.Id == id);
            if (slipper == null)
            {
                return NotFound();
            }

            return View(slipper);
        }

        // GET: Slippers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Slippers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TypeOfProduct,Department,Price,Size,Width,Material,DescOfProduct,ManufacturingDt")] Slipper slipper)
        {
            if (ModelState.IsValid)
            {
                _context.Add(slipper);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(slipper);
        }

        // GET: Slippers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slipper = await _context.Slipper.FindAsync(id);
            if (slipper == null)
            {
                return NotFound();
            }
            return View(slipper);
        }

        // POST: Slippers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TypeOfProduct,Department,Price,Size,Width,Material,DescOfProduct,ManufacturingDt")] Slipper slipper)
        {
            if (id != slipper.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(slipper);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SlipperExists(slipper.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(slipper);
        }

        // GET: Slippers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var slipper = await _context.Slipper
                .FirstOrDefaultAsync(m => m.Id == id);
            if (slipper == null)
            {
                return NotFound();
            }

            return View(slipper);
        }

        // POST: Slippers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var slipper = await _context.Slipper.FindAsync(id);
            _context.Slipper.Remove(slipper);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SlipperExists(int id)
        {
            return _context.Slipper.Any(e => e.Id == id);
        }
    }
}

Views/Slippers/Create.cshtml
@model Flex_Slippers.Models.Slipper

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Slipper</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TypeOfProduct" class="control-label"></label>
                <input asp-for="TypeOfProduct" class="form-control" />
                <span asp-validation-for="TypeOfProduct" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Size" class="control-label"></label>
                <input asp-for="Size" class="form-control" />
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width" class="control-label"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Material" class="control-label"></label>
                <input asp-for="Material" class="form-control" />
                <span asp-validation-for="Material" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescOfProduct" class="control-label"></label>
                <input asp-for="DescOfProduct" class="form-control" />
                <span asp-validation-for="DescOfProduct" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturingDt" class="control-label"></label>
                <input asp-for="ManufacturingDt" class="form-control" />
                <span asp-validation-for="ManufacturingDt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Slippers/Delete.cshtml
@model Flex_Slippers.Models.Slipper

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Slipper</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfProduct)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TypeOfProduct)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Size)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Size)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Width)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Width)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Material)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Material)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DescOfProduct)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DescOfProduct)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ManufacturingDt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturingDt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Slippers/Details.cshtml
@model Flex_Slippers.Models.Slipper

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Slipper</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TypeOfProduct)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TypeOfProduct)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Size)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Size)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Width)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Width)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Material)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Material)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DescOfProduct)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DescOfProduct)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ManufacturingDt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ManufacturingDt)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Slippers/Edit.cshtml
@model Flex_Slippers.Models.Slipper

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Slipper</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="TypeOfProduct" class="control-label"></label>
                <input asp-for="TypeOfProduct" class="form-control" />
                <span asp-validation-for="TypeOfProduct" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Department" class="control-label"></label>
                <input asp-for="Department" class="form-control" />
                <span asp-validation-for="Department" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Size" class="control-label"></label>
                <input asp-for="Size" class="form-control" />
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Width" class="control-label"></label>
                <input asp-for="Width" class="form-control" />
                <span asp-validation-for="Width" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Material" class="control-label"></label>
                <input asp-for="Material" class="form-control" />
                <span asp-validation-for="Material" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescOfProduct" class="control-label"></label>
                <input asp-for="DescOfProduct" class="form-control" />
                <span asp-validation-for="DescOfProduct" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturingDt" class="control-label"></label>
                <input asp-for="ManufacturingDt" class="form-control" />
                <span asp-validation-for="ManufacturingDt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Slippers/Index.cshtml
@*@model IEnumerable<Flex_Slippers.Models.Slipper>*@

@model Flex_Slippers.Models.SlipperMaterialViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>


<form asp-controller="Slippers" asp-action="Index" method="get">
    <p>
        Material : 
        <select asp-for="SlipperMaterial" asp-items="Model.Materials">
            <option value="">All</option>
        </select>

        Deparment: 
        <input type="text" asp-for="SearchString" />
        <input type="submit" value="Filter" />
    </p>
</form>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Slippers[0].TypeOfProduct)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Slippers[0].Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Slippers[0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Slippers[0].Size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Slippers[0].Width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Slippers[0].Material)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Slippers[0].DescOfProduct)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Slippers[0].Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Slippers[0].ManufacturingDt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Slippers) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TypeOfProduct)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Size)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Width)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Material)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DescOfProduct)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManufacturingDt)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>